version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: dynamic-mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dynamic_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - dynamic-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: dynamic-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - dynamic-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: dynamic-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - dynamic-network

  app:
    build: .
    container_name: dynamic-mongo-app
    depends_on:
      - mongodb
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/dynamic_db
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - dynamic-network

volumes:
  mongodb_data:

networks:
  dynamic-network:
    driver: bridge
