version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: dynamic-mongo-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dynamic_db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
